name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  geolocator: ^14.0.0
  flutter_launcher_icons: ^0.14.3
  fl_chart: ^0.71.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-200.ttf
          weight: 200
        - asset: assets/fonts/Nunito-400.ttf
          weight: 400
        - asset: assets/fonts/Nunito-500.ttf
          weight: 500
        - asset: assets/fonts/Nunito-600.ttf
          weight: 600
        - asset: assets/fonts/Nunito-700.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/fonts/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_app_icon.png"